spring:
  application:
    name: ribbonClientA
server:
  port: 9213


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka

#ribbon:
#  eager-load:
#      enabled: true
#      clients: HELLOSERVER,HELLOSERVER1


# hystrix dashboard streammanagement.
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream